[controller]
file = "KaFa_1500_v9.py"

[deploy]
check_drone_start_pos = true
check_race_track = true
real_track_objects = true

[[deploy.drones]]
id = 52
channel = 80
drone_model = "cf21B_500"

[env]
control_mode = "attitude"
freq = 50
id = "DroneRacing-v0"
seed = -1
sensor_range = 0.7

[sim]
attitude_freq = 500
camera = -1
drone_model = "cf21B_500"
freq = 500
physics = "first_principles"
render = true

[[sim.cam_config]]
distance = 5.0
azimuth = 180.0
elevation = -25.0
lookat = [0.0, 0.0, 0.0]

[env.track]
randomize = false


[[env.track.drones]]
pos = [0.2346, 0.6914, 0.0300]
rpy = [0.0000, 0.0000, 0.0000]
vel = [0, 0, 0]
ang_vel = [0, 0, 0]

[[env.track.gates]]
pos = [-0.3124, 0.7485, 0.5351]
rpy = [0.0000, 0.0000, 3.0376]

[[env.track.gates]]
pos = [-1.4249, 0.0159, 0.5892]
rpy = [0.0000, 0.0000, -1.2423]

[[env.track.gates]]
pos = [0.3217, -1.1115, 1.3971]
rpy = [0.0000, 0.0000, -0.1040]

[[env.track.gates]]
pos = [1.4062, -0.2796, 1.4468]
rpy = [0.0000, 0.0000, 1.8993]

[[env.track.obstacles]]
pos = [0.6686, -0.0007, 1.5430]

[[env.track.obstacles]]
pos = [-1.2110, 0.8760, 1.5595]

[[env.track.obstacles]]
pos = [0.8552, 0.6675, 1.5423]

[[env.track.obstacles]]
pos = [-1.2917, -0.6401, 1.5438]

[env.disturbances.action]
fn = "normal"
scale = 0.001

[env.disturbances.dynamics]
fn = "uniform"

[env.randomizations.drone_inertia]
fn = "uniform"

[env.randomizations.drone_mass]
fn = "uniform"

[env.randomizations.drone_pos]
fn = "uniform"

[env.randomizations.drone_rpy]
fn = "uniform"

[env.randomizations.gate_pos]
fn = "uniform"

[env.randomizations.gate_rpy]
fn = "uniform"

[env.randomizations.obstacle_pos]
fn = "uniform"

[env.track.safety_limits]
pos_limit_high = [2.5, 1.5, 2.0]
pos_limit_low = [-2.5, -1.5, -0.001]

[env.disturbances.dynamics.kwargs]
maxval = [0.1, 0.1, 0.1]
minval = [-0.1, -0.1, -0.1]

[env.randomizations.drone_inertia.kwargs]
maxval = [1e-6, 1e-6, 1e-6]
minval = [-1e-6, -1e-6, -1e-6]

[env.randomizations.drone_mass.kwargs]
maxval = 0.005
minval = -0.005

[env.randomizations.drone_pos.kwargs]
maxval = [0.1, 0.1, 0.02]
minval = [-0.1, -0.1, 0.0]

[env.randomizations.drone_rpy.kwargs]
maxval = [0.1, 0.1, 0.1]
minval = [-0.1, -0.1, -0.1]

[env.randomizations.gate_pos.kwargs]
maxval = [0.15, 0.15, 0.1]
minval = [-0.15, -0.15, -0.1]

[env.randomizations.gate_rpy.kwargs]
maxval = [0.05, 0.1, 0.2]
minval = [-0.05, -0.1, -0.2]

[env.randomizations.obstacle_pos.kwargs]
maxval = [0.15, 0.15, 0.05]
minval = [-0.15, -0.15, -0.05]
